[package]
name = "flow"
version = "0.1.0"
edition = "2024"

[dependencies]
evalexpr =  { workspace = true }
log =  { workspace = true }
serde =  { workspace = true }
serde_json =  { workspace = true }
thiserror =  { workspace = true }
tokio =  { workspace = true }
