control-plane:
  listen:
    ip: 127.0.0.1
    port: 4000
  database:
    driver: sqlite
    database: ./control_plane.sqlite

log_level: "info"

modules:
  tracing:
    enabled: true
    otlp_endpoint: http://jaeger:4317
  metrics:
    enabled: true
    port: 9090
