control-plane:
  listen:
    ip: 0.0.0.0
    port: 4000
  database:
    driver: sqlite
    database: /app/data/control_plane.sqlite

log_level: "info"

modules:
  openapi_docs:
    enabled: false
    port: 3001
