listeners:
  - port: 3000
    ip: 0.0.0.0
    protocol: HTTP
    routes:
    - name: v1
      matches:
      - path:
          pathPrefix: /v1
        method: GET
    - name: v2
      matches:
      - path:
          pathPrefix: /v2
        method: GET
