name: Build and Deploy Plugins

on:
  # workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  build_darwin:
    runs-on: macos-latest
    env:
      OS_SUFFIX: -darwin-aarch64
      TARGET: aarch64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run plugins script
        run: ./shell/build-plugins.sh

      - name: Upload Mac plugins
        uses: actions/upload-artifact@v4
        with:
          name: darwin-plugins
          path: ./plugins
          retention-days: 1

  build_linux_amd64:
    runs-on: ubuntu-latest
    env:
      OS_SUFFIX: -linux-amd64
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run plugins script
        run: TARGET=x86_64-unknown-linux-gnu ./shell/build-plugins.sh

      - name: Upload Linux amd64 plugins
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-plugins
          path: ./plugins
          retention-days: 1
  
  build_linux_aarch64:
    runs-on: ubuntu-latest
    env:
      OS_SUFFIX: -linux-aarch64
      TARGET: aarch64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run plugins script
        run: TARGET=aarch64-unknown-linux-gnu ./shell/build-plugins.sh

      - name: Upload Linux aarch64 plugins
        uses: actions/upload-artifact@v4
        with:
          name: linux-aarch64-plugins
          path: ./plugins
          retention-days: 1

  deploy:
    needs: 
      - build_darwin
      - build_linux_amd64
      - build_linux_aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create raw directory
        run: mkdir -p raw

      - name: Download Mac plugins
        uses: actions/download-artifact@v4
        with:
          name: darwin-plugins
          path: darwin-plugins

      - name: Download Ubuntu plugins
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64-plugins
          path: linux-amd64-plugins

      - name: Download Linux musl plugins
        uses: actions/download-artifact@v4
        with:
          name: linux-aarch64-plugins
          path: linux-aarch64-plugins

      - name: Move artifacts to raw directory
        run: |
          cp darwin-plugins/*.tar.gz raw/ || true
          cp linux-amd64-plugins/*.tar.gz raw/ || true
          cp linux-aarch64-plugins/*.tar.gz raw/ || true

      - name: Run resolver script
        run: ./scripts/resolver-plugins-dir.sh

      - name: Setup Git for plugins repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Update plugins repository
        env:
          GH_TOKEN: ${{ secrets.GH_PAT  }}
        run: |
          cp -R plugins/* apify-plugins/plugins/
          cd apify-plugins
          git checkout -b update-plugins-${{ github.run_id }}
          git add .
          git commit -m "Update plugins from workflow run ${{ github.run_id }}" || echo "No changes to commit"
          git push --set-upstream origin update-plugins-${{ github.run_id }}
          gh pr create --title "Update plugins from workflow run ${{ github.run_id }}" --body "Automated plugin update from workflow run." --base main --head update-plugins-${{ github.run_id }}
