name: Build and Deploy Plugins

on:
  # workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  build_linux_amd64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use_cross: false }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use_cross: true }
          - { os: macos-latest,  target: x86_64-apple-darwin, use_cross: true }
          - { os: macos-latest,  target: aarch64-apple-darwin, use_cross: false }

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        env:
          TARGET: ${{ matrix.target }}
          CROSS: ${{ matrix.use_cross }}
          OS: ${{ matrix.os }}
        run: ./shell/build-plugins.sh

      - name: Upload Linux amd64 plugins
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-plugins
          path: ./plugins-target
          retention-days: 1
  
      - name: Setup Git for plugins repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Update plugins repository
        env:
          GH_TOKEN: ${{ secrets.GH_PLUGINS_PAT  }}
        run: |
          gh repo clone apifyhost/apify-plugins
          cp -R plugins-target/* apify-plugins/plugins/
          cd apify-plugins
          git checkout -b update-plugins-${{ github.run_id }}
          git add .
          git commit -m "Update plugins from workflow run ${{ github.run_id }}" || echo "No changes to commit"
          gh repo push origin update-plugins-${{ github.run_id }}
          gh pr create --title "Update plugins from workflow run ${{ github.run_id }}" --body "Automated plugin update from workflow run." --base main --head update-plugins-${{ github.run_id }}
