name: Build and Deploy Plugins

on:
  # workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use_cross: false }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use_cross: true }
          - { os: macos-latest,  target: x86_64-apple-darwin, use_cross: false }
          - { os: macos-latest,  target: aarch64-apple-darwin, use_cross: false }

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        env:
          TARGET: ${{ matrix.target }}
          CROSS: ${{ matrix.use_cross }}
          OS: ${{ matrix.os }}
        run: ./shell/build-plugins.sh

      - name: Upload Linux amd64 plugins
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ./plugins-target
          retention-days: 1

  release:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create raw directory
        run: mkdir -p raw

      - name: Download Mac plugins
        uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: x86_64-apple-darwin

      - name: Download Mac aarch64 plugins
        uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: aarch64-apple-darwin

      - name: Download Linux plugins
        uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
          path: x86_64-unknown-linux-gnu

      - name: Download Linux aarch64 plugins
        uses: actions/download-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu
          path: aarch64-unknown-linux-gnu

      - name: Move artifacts to raw directory
        run: |
          cp aarch64-apple-darwin/*.tar.gz raw/ || true
          cp x86_64-apple-darwin/*.tar.gz raw/ || true
          cp x86_64-unknown-linux-gnu/*.tar.gz raw/ || true
          cp aarch64-unknown-linux-gnu/*.tar.gz raw/ || true

      - name: Setup Git for plugins repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      - name: Update plugins repository
        env:
          GH_TOKEN: ${{ secrets.PLUGINS_TOKEN  }}
        run: |
          ls -l raw
          VERSION=${GITHUB_REF##*/}
          if [[ "$VERSION" = "refs/heads/main" || "$VERSION" = "merge" ]]; then
            VERSION="latest"
          fi
          echo "Using version: $VERSION"
          gh auth login --with-token <<< "$GH_TOKEN"
          gh repo clone apifyhost/apify-plugins
          mkdir -p apify-plugins/plugins/${VERSION}
          cp -R raw/* apify-plugins/plugins/${VERSION}/
          cd apify-plugins
          git checkout -b update-plugins-${{ github.run_id }}
          git add .
          git commit -m "Update plugins from workflow run ${{ github.run_id }}" || echo "No changes to commit"
          # gh repo push origin update-plugins-${{ github.run_id }}
          git push --set-upstream origin update-plugins-${{ github.run_id }}
          gh pr create --title "Update plugins from workflow run ${{ github.run_id }}" --body "Automated plugin update from workflow run." --base main --head update-plugins-${{ github.run_id }}
